//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.20 at 04:08:06 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://byminsk.kes/soapsecured", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package by.minsk.kes.soap.secured.soapsecured.model;
